In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

In [3]:
!curl -O https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  1  291k    1  3582    0     0  11593      0  0:00:25 --:--:--  0:00:25 11592

100  291k  100  291k    0     0   491k      0 --:--:-- --:--:-- --:--:--  491k
100  291k  100  291k    0     0   491k      0 --:--:-- --:--:-- --:--:--  491k


In [4]:
!cat laptops.csv | head











cat: stdout: Broken pipe










cat: stdout: Broken pipe


In [5]:
data = pd.read_csv('laptops.csv', sep=',')

In [6]:
data.head()

Laptop Status  ... Touch Final Price
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New  ...    No     1009.00
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  ...    No      299.00
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New  ...    No      789.00
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New  ...    No     1199.00
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New  ...    No      669.01

[5 rows x 12 columns]

In [7]:
len(data)

2160

In [8]:
data.Brand.nunique()

27

In [9]:
data.isna().sum()[data.isna().sum() > 0]

Storage type      42
GPU             1371
Screen             4
dtype: int64

In [10]:
data[data['Brand'] == 'Dell']['Final Price'].max()

3936.0

In [11]:
data['Screen'].median()

15.6

In [12]:
data['Screen'].value_counts().head()

Screen
15.6    1009
14.0     392
16.0     174
17.3     161
13.3     131
Name: count, dtype: int64

In [13]:
filled_screen = data['Screen'].fillna(15.6)

In [14]:
filled_screen.median()

15.6

In [15]:
#last task solution from here

In [16]:
sow = data[data['Brand'] == 'Innjoo'] [['RAM', 'Storage', 'Screen']]
sow

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [17]:
import numpy as np

In [18]:
X = np.array(sow)

In [19]:
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [20]:
X_transpos = X.T

In [21]:
X_transpos

array([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
       [256. , 512. ,  64. ,  64. , 128. , 128. ],
       [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [22]:
XTX = X_transpos.dot(X)

In [23]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [24]:
XTX_inverse = np.linalg.inv(XTX)

In [25]:
XTX_inverse

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [26]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [27]:
y

array([1100, 1300,  800,  900, 1000, 1100])

In [28]:
w = XTX_inverse.dot(X_transpos).dot(y)

In [29]:
w.sum()

91.2998806299557