In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

import matplotlib.pyplot as plt

In [2]:
print(pd.__version__)

2.2.3



## Homework

> Note: sometimes your answer doesn't match one of the options exactly. 
> That's fine. 
> Select the option that's closest to your solution.


### Dataset

In this homework, we will use the Bank Marketing dataset. Download it from [here](https://archive.ics.uci.edu/static/public/222/bank+marketing.zip).

Or you can do it with `wget`:

```bash
wget https://archive.ics.uci.edu/static/public/222/bank+marketing.zip
```

We need to take `bank/bank-full.csv` file from the downloaded zip-file.  
In this dataset our desired target for classification task will be `y` variable - has the client subscribed a term deposit or not. 

In [3]:
#!curl -O https://archive.ics.uci.edu/static/public/222/bank+marketing.zip

In [4]:
#!unzip bank+marketing.zip

In [5]:
#!ls

In [6]:
#!unzip bank.zip

In [7]:
df = pd.read_csv('bank-full.csv', sep=';', header=0)
df

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

For the rest of the homework, you'll need to use only these columns:

* `age`,
* `job`,
* `marital`,
* `education`,
* `balance`,
* `housing`,
* `contact`,
* `day`,
* `month`,
* `duration`,
* `campaign`,
* `pdays`,
* `previous`,
* `poutcome`,
* `y`

### Data preparation

* Select only the features from above.
* Check if the missing values are presented in the features.


In [8]:
needed_cols = ['age', 'job', 'marital', 'education', 'balance', 'housing', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']


In [9]:
df = df[needed_cols]
df

age           job   marital  education  balance housing    contact  \
0       58    management   married   tertiary     2143     yes    unknown   
1       44    technician    single  secondary       29     yes    unknown   
2       33  entrepreneur   married  secondary        2     yes    unknown   
3       47   blue-collar   married    unknown     1506     yes    unknown   
4       33       unknown    single    unknown        1      no    unknown   
...    ...           ...       ...        ...      ...     ...        ...   
45206   51    technician   married   tertiary      825      no   cellular   
45207   71       retired  divorced    primary     1729      no   cellular   
45208   72       retired   married  secondary     5715      no   cellular   
45209   57   blue-collar   married  secondary      668      no  telephone   
45210   37  entrepreneur   married  secondary     2971      no   cellular   

       day month  duration  campaign  pdays  previous poutcome    y  
0        5   may       261         1     -1         0  unknown   no  
1        5   may       151         1     -1         0  unknown   no  
2        5   may        76         1     -1         0  unknown   no  
3        5   may        92         1     -1         0  unknown   no  
4        5   may       198         1     -1         0  unknown   no  
...    ...   ...       ...       ...    ...       ...      ...  ...  
45206   17   nov       977         3     -1         0  unknown  yes  
45207   17   nov       456         2     -1         0  unknown  yes  
45208   17   nov      1127         5    184         3  success  yes  
45209   17   nov       508         4     -1         0  unknown   no  
45210   17   nov       361         2    188        11    other   no  

[45211 rows x 15 columns]

In [10]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

### Question 1

What is the most frequent observation (mode) for the column `education`?

- `unknown`
- `primary`
- `secondary`
- `tertiary`



In [11]:
df.education.value_counts().reset_index().head()

education  count
0  secondary  23202
1   tertiary  13301
2    primary   6851
3    unknown   1857

### Question 2

Create the [correlation matrix](https://www.google.com/search?q=correlation+matrix) for the numerical features of your dataset. 
In a correlation matrix, you compute the correlation coefficient between every pair of features.

What are the two features that have the biggest correlation?

- `age` and `balance`
- `day` and `campaign`
- `day` and `pdays`
- `pdays` and `previous`

In [12]:
numericals = list(df.dtypes[df.dtypes != 'object'].index)
numericals

['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

In [13]:
corr_dict = {}
for i in numericals:
    for j in numericals:
        if i != j:
            corr = df[i].corr(df[j])
            corr_dict[f'{i} and {j} coorrelation is: '] = corr
        

In [14]:
# Find the key with the maximum value in the dictionary
max_key = max(corr_dict, key=corr_dict.get)

# Get the maximum value
max_value = corr_dict[max_key]

# Print the key and the value
print(f'The highest correlation is {max_key} with a value of {max_value}')


The highest correlation is pdays and previous coorrelation is:  with a value of 0.45481963548050097


In [15]:
corr_matrix = df[numericals].corr()
corr_matrix

age   balance       day  duration  campaign     pdays  previous
age       1.000000  0.097783 -0.009120 -0.004648  0.004760 -0.023758  0.001288
balance   0.097783  1.000000  0.004503  0.021560 -0.014578  0.003435  0.016674
day      -0.009120  0.004503  1.000000 -0.030206  0.162490 -0.093044 -0.051710
duration -0.004648  0.021560 -0.030206  1.000000 -0.084570 -0.001565  0.001203
campaign  0.004760 -0.014578  0.162490 -0.084570  1.000000 -0.088628 -0.032855
pdays    -0.023758  0.003435 -0.093044 -0.001565 -0.088628  1.000000  0.454820
previous  0.001288  0.016674 -0.051710  0.001203 -0.032855  0.454820  1.000000

In [16]:
 #Get the two largest correlations (excluding the diagonal)
corr_matrix_no_diag = corr_matrix.where(~np.eye(corr_matrix.shape[0], dtype=bool))
largest_corrs = corr_matrix_no_diag.unstack().nlargest(2)

# Print the two largest correlations
print(largest_corrs)

pdays     previous    0.45482
previous  pdays       0.45482
dtype: float64


In [17]:
corr_series = corr_matrix.unstack()
corr_series

age       age         1.000000
          balance     0.097783
          day        -0.009120
          duration   -0.004648
          campaign    0.004760
          pdays      -0.023758
          previous    0.001288
balance   age         0.097783
          balance     1.000000
          day         0.004503
          duration    0.021560
          campaign   -0.014578
          pdays       0.003435
          previous    0.016674
day       age        -0.009120
          balance     0.004503
          day         1.000000
          duration   -0.030206
          campaign    0.162490
          pdays      -0.093044
          previous   -0.051710
duration  age        -0.004648
          balance     0.021560
          day        -0.030206
          duration    1.000000
          campaign   -0.084570
          pdays      -0.001565
          previous    0.001203
campaign  age         0.004760
          balance    -0.014578
          day         0.162490
          duration   -0.084570
        

In [18]:
corr_series = corr_series[corr_series < 1]
corr_series

age       balance     0.097783
          day        -0.009120
          duration   -0.004648
          campaign    0.004760
          pdays      -0.023758
          previous    0.001288
balance   age         0.097783
          day         0.004503
          duration    0.021560
          campaign   -0.014578
          pdays       0.003435
          previous    0.016674
day       age        -0.009120
          balance     0.004503
          duration   -0.030206
          campaign    0.162490
          pdays      -0.093044
          previous   -0.051710
duration  age        -0.004648
          balance     0.021560
          day        -0.030206
          campaign   -0.084570
          pdays      -0.001565
          previous    0.001203
campaign  age         0.004760
          balance    -0.014578
          day         0.162490
          duration   -0.084570
          pdays      -0.088628
          previous   -0.032855
pdays     age        -0.023758
          balance     0.003435
        

In [19]:
max_corr = corr_series.idxmax()
max_corr
#//NOTE: the answer is pdays and previous

('pdays', 'previous')

In [20]:
max_value = corr_series.max()
max_value

0.4548196354805043

### Target encoding

* Now we want to encode the `y` variable.
* Let's replace the values `yes`/`no` with `1`/`0`.


In [21]:
df['y'] = (df['y'] == 'yes').astype(int)

/var/folders/5f/8m68q7196_78q45h5j1_83980000gn/T/ipykernel_61000/2070099191.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['y'] = (df['y'] == 'yes').astype(int)


In [22]:
df

age           job   marital  education  balance housing    contact  \
0       58    management   married   tertiary     2143     yes    unknown   
1       44    technician    single  secondary       29     yes    unknown   
2       33  entrepreneur   married  secondary        2     yes    unknown   
3       47   blue-collar   married    unknown     1506     yes    unknown   
4       33       unknown    single    unknown        1      no    unknown   
...    ...           ...       ...        ...      ...     ...        ...   
45206   51    technician   married   tertiary      825      no   cellular   
45207   71       retired  divorced    primary     1729      no   cellular   
45208   72       retired   married  secondary     5715      no   cellular   
45209   57   blue-collar   married  secondary      668      no  telephone   
45210   37  entrepreneur   married  secondary     2971      no   cellular   

       day month  duration  campaign  pdays  previous poutcome  y  
0        5   may       261         1     -1         0  unknown  0  
1        5   may       151         1     -1         0  unknown  0  
2        5   may        76         1     -1         0  unknown  0  
3        5   may        92         1     -1         0  unknown  0  
4        5   may       198         1     -1         0  unknown  0  
...    ...   ...       ...       ...    ...       ...      ... ..  
45206   17   nov       977         3     -1         0  unknown  1  
45207   17   nov       456         2     -1         0  unknown  1  
45208   17   nov      1127         5    184         3  success  1  
45209   17   nov       508         4     -1         0  unknown  0  
45210   17   nov       361         2    188        11    other  0  

[45211 rows x 15 columns]

### Split the data

* Split your data in train/val/test sets with 60%/20%/20% distribution.
* Use Scikit-Learn for that (the `train_test_split` function) and set the seed to `42`.
* Make sure that the target value `y` is not in your dataframe.

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
df_full_train, df_test = train_test_split(df, test_size = 0.2, random_state= 42)
df_train, df_val = train_test_split(df_full_train, test_size = 0.25, random_state= 42)

len(df_train), len(df_val), len(df_test)

(27126, 9042, 9043)

In [25]:
y_full_train = df_full_train['y'].values
y_train = df_train['y'].values
y_val = df_val['y'].values
y_test = df_test['y'].values

In [26]:
del df_train['y']
del df_val['y']
del df_test['y']

### Question 3

* Calculate the mutual information score between `y` and other categorical variables in the dataset. Use the training set only.
* Round the scores to 2 decimals using `round(score, 2)`.

Which of these variables has the biggest mutual information score?
  
- `contact`
- `education`
- `housing`
- `poutcome`

In [27]:
from sklearn.metrics import mutual_info_score

In [28]:
categoricals = list(df.dtypes[df.dtypes == 'object'].index)
categoricals

['job', 'marital', 'education', 'housing', 'contact', 'month', 'poutcome']

In [29]:
df[categoricals]

job   marital  education housing    contact month poutcome
0        management   married   tertiary     yes    unknown   may  unknown
1        technician    single  secondary     yes    unknown   may  unknown
2      entrepreneur   married  secondary     yes    unknown   may  unknown
3       blue-collar   married    unknown     yes    unknown   may  unknown
4           unknown    single    unknown      no    unknown   may  unknown
...             ...       ...        ...     ...        ...   ...      ...
45206    technician   married   tertiary      no   cellular   nov  unknown
45207       retired  divorced    primary      no   cellular   nov  unknown
45208       retired   married  secondary      no   cellular   nov  success
45209   blue-collar   married  secondary      no  telephone   nov  unknown
45210  entrepreneur   married  secondary      no   cellular   nov    other

[45211 rows x 7 columns]

In [30]:
mutual_info_score(df_train.job, y_train)

0.007316082778474635

In [31]:
def mutual_information_subscribed_score(series):
    return mutual_info_score(series, y_train)

In [32]:
mis = df_train[categoricals].apply(mutual_information_subscribed_score)
mis.sort_values(ascending=False)

poutcome     0.029533
month        0.025090
contact      0.013356
housing      0.010343
job          0.007316
education    0.002697
marital      0.002050
dtype: float64

### Question 4

* Now let's train a logistic regression.
* Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
* Fit the model on the training dataset.
    - To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
    - `model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)`
* Calculate the accuracy on the validation dataset and round it to 2 decimal digits.

What accuracy did you get?

- 0.6
- 0.7
- 0.8
- 0.9

In [33]:
from sklearn.feature_extraction import DictVectorizer

In [34]:
train_dicts = df_train[categoricals + numericals].to_dict(orient= 'records')
train_dicts

[{'job': 'technician',
  'marital': 'single',
  'education': 'tertiary',
  'housing': 'yes',
  'contact': 'cellular',
  'month': 'aug',
  'poutcome': 'unknown',
  'age': 32,
  'balance': 1100,
  'day': 11,
  'duration': 67,
  'campaign': 1,
  'pdays': -1,
  'previous': 0},
 {'job': 'entrepreneur',
  'marital': 'married',
  'education': 'secondary',
  'housing': 'yes',
  'contact': 'cellular',
  'month': 'nov',
  'poutcome': 'unknown',
  'age': 38,
  'balance': 0,
  'day': 17,
  'duration': 258,
  'campaign': 1,
  'pdays': -1,
  'previous': 0},
 {'job': 'blue-collar',
  'marital': 'married',
  'education': 'secondary',
  'housing': 'yes',
  'contact': 'cellular',
  'month': 'may',
  'poutcome': 'unknown',
  'age': 49,
  'balance': 3309,
  'day': 15,
  'duration': 349,
  'campaign': 2,
  'pdays': -1,
  'previous': 0},
 {'job': 'housemaid',
  'marital': 'married',
  'education': 'primary',
  'housing': 'no',
  'contact': 'cellular',
  'month': 'aug',
  'poutcome': 'unknown',
  'age': 37,


In [35]:
dv = DictVectorizer(sparse= False)

In [36]:
X_train = dv.fit_transform(train_dicts)

In [37]:
dv.get_feature_names_out()

array(['age', 'balance', 'campaign', 'contact=cellular',
       'contact=telephone', 'contact=unknown', 'day', 'duration',
       'education=primary', 'education=secondary', 'education=tertiary',
       'education=unknown', 'housing=no', 'housing=yes', 'job=admin.',
       'job=blue-collar', 'job=entrepreneur', 'job=housemaid',
       'job=management', 'job=retired', 'job=self-employed',
       'job=services', 'job=student', 'job=technician', 'job=unemployed',
       'job=unknown', 'marital=divorced', 'marital=married',
       'marital=single', 'month=apr', 'month=aug', 'month=dec',
       'month=feb', 'month=jan', 'month=jul', 'month=jun', 'month=mar',
       'month=may', 'month=nov', 'month=oct', 'month=sep', 'pdays',
       'poutcome=failure', 'poutcome=other', 'poutcome=success',
       'poutcome=unknown', 'previous'], dtype=object)

In [38]:
val_dicts = df_val[categoricals + numericals].to_dict(orient= 'records')

In [39]:
X_val = dv.transform(val_dicts)

In [40]:
X_train.shape, X_val.shape

((27126, 47), (9042, 47))

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [43]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [44]:
model.predict(X_train)

array([0, 0, 0, ..., 0, 1, 0])

In [45]:
model.predict_proba(X_train)

array([[0.96831215, 0.03168785],
       [0.96890418, 0.03109582],
       [0.93337122, 0.06662878],
       ...,
       [0.99121962, 0.00878038],
       [0.2376122 , 0.7623878 ],
       [0.86165266, 0.13834734]])

In [46]:
y_pred = model.predict_proba(X_val)[:, 1]
y_pred

array([0.01249077, 0.00926422, 0.14663636, ..., 0.05021294, 0.00872845,
       0.27989186])

In [47]:
subscribe_decision = (y_pred > 0.5)

In [48]:
subscribe_decision

array([False, False, False, ..., False, False, False])

In [49]:
(y_val == subscribe_decision).mean()

0.9014598540145985

In [50]:
#//NOTE: nézzük meg ,hogy mi az eredmény ha predict_proba, helyett csak a predicttel nézem

In [51]:
y_pred = model.predict(X_val)
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [52]:
(y_val == y_pred).mean()

0.9014598540145985

### Question 5 

* Let's find the least useful feature using the *feature elimination* technique.
* Train a model with all these features (using the same parameters as in Q4).
* Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
* For each feature, calculate the difference between the original accuracy and the accuracy without the feature. 

Which of following feature has the smallest difference?

- `age`
- `balance`
- `marital`
- `previous`

> **Note**: The difference doesn't have to be positive.

In [53]:
df.head()

age           job  marital  education  balance housing  contact  day month  \
0   58    management  married   tertiary     2143     yes  unknown    5   may   
1   44    technician   single  secondary       29     yes  unknown    5   may   
2   33  entrepreneur  married  secondary        2     yes  unknown    5   may   
3   47   blue-collar  married    unknown     1506     yes  unknown    5   may   
4   33       unknown   single    unknown        1      no  unknown    5   may   

   duration  campaign  pdays  previous poutcome  y  
0       261         1     -1         0  unknown  0  
1       151         1     -1         0  unknown  0  
2        76         1     -1         0  unknown  0  
3        92         1     -1         0  unknown  0  
4       198         1     -1         0  unknown  0

In [54]:
all_features = categoricals + numericals
omitt = ['age', 'balance', 'marital', 'previous']

In [55]:
original_accuracy = (y_val == subscribe_decision).mean()

fe_dictionary = {}

for i in omitt:
    df_train_omitt = df_train.copy()
    df_val_omitt = df_val.copy()
    del df_train_omitt[i]
    del df_val_omitt[i]
    train_dicts = df_train_omitt.to_dict(orient= 'records')
    X_train = dv.fit_transform(train_dicts)
    val_dicts = df_val_omitt.to_dict(orient= 'records')
    X_val = dv.transform(val_dicts)
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_val)[:, 1]
    subscribe_decision = (y_pred > 0.5)
    accuracy = (y_val == subscribe_decision).mean()
    print(f'The accuracy without {i} feature is {accuracy} compare to {original_accuracy} which is the "original accuracy"')
    print()
    decrease_in_accuracy = original_accuracy - accuracy
    fe_dictionary[i] = decrease_in_accuracy

sorted_dict = dict(sorted(fe_dictionary.items(), key=lambda item: item[1], reverse=True))
sorted_dict
    

The accuracy without age feature is 0.9007962840079629 compare to 0.9014598540145985 which is the "original accuracy"

The accuracy without balance feature is 0.9007962840079629 compare to 0.9014598540145985 which is the "original accuracy"

The accuracy without marital feature is 0.9000221190002212 compare to 0.9014598540145985 which is the "original accuracy"

The accuracy without previous feature is 0.9012386640123866 compare to 0.9014598540145985 which is the "original accuracy"



{'marital': 0.0014377350143772727,
 'age': 0.0006635700066356387,
 'balance': 0.0006635700066356387,
 'previous': 0.00022119000221187957}

### Question 6

* Now let's train a regularized logistic regression.
* Let's try the following values of the parameter `C`: `[0, 0.01, 0.1, 1, 10]`.
* Train models using all the features as in Q4.
* Calculate the accuracy on the validation dataset and round it to 3 decimal digits.

Which of these `C` leads to the best accuracy on the validation set?

- 0.01
- 0.1
- 1
- 10
- 100

> **Note**: If there are multiple options, select the smallest `C`.

In [56]:
original_accuracy = (y_val == subscribe_decision).mean()

regs = [0.001, 0.01, 0.1, 1, 10]

reg_dictionary = {}


for i in regs:
    model = LogisticRegression(solver='liblinear', C=i, max_iter=1000, random_state=42)
    df_train = df_train.copy()
    df_val = df_val.copy()
    train_dicts = df_train[categoricals + numericals].to_dict(orient= 'records')
    X_train = dv.fit_transform(train_dicts)
    val_dicts = df_val[categoricals + numericals].to_dict(orient= 'records')
    X_val = dv.transform(val_dicts)
    model.fit(X_train, y_train)
    y_pred = model.predict_proba(X_val)[:, 1]
    subscribe_decision = (y_pred > 0.5)
    accuracy = (y_val == subscribe_decision).mean()
    print(f'The accuracy with {i} regularization is {accuracy}')
    
    reg_dictionary[i] = accuracy.round(3)


sorted_reg_dict = dict(sorted(reg_dictionary.items(), key=lambda item: item[1], reverse=True))
sorted_reg_dict


The accuracy with 0.001 regularization is 0.8904003539040035
The accuracy with 0.01 regularization is 0.8976996239769962
The accuracy with 0.1 regularization is 0.900575094005751
The accuracy with 1 regularization is 0.9014598540145985
The accuracy with 10 regularization is 0.9010174740101747


{0.1: 0.901, 1: 0.901, 10: 0.901, 0.01: 0.898, 0.001: 0.89}